# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora --enable-wayland-ime
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password
bind = SUPER,x , exec, omarchy-cmd-screenshot
bind = SUPER,E, exec, 
wsbind =1,DP-1
wsbind =2,DP-1
wsbind =3,DP-1

bind = SUPER SHIFT,l , exec,  /bin/bash /home/moritz/programming/bash_scripts/change_wallpaper.sh

#unbind = SUPER, SPACE
#
#bind = SUPER, SPACE,exec , /home/moritz/programming/app-launcher/app-launcher/dist/Orbital-0.0.0.AppImage
#bind = SUPER, SPACE, exec, ghostty -e bash -c 'echo -ne "\033]0;nero-launcher\007"; exec /home/moritz/programming/bash_scripts/start_nero_launcher.sh'

# Window bindings
wsbind = SUPER SHIFT, 1, exec, uwsm-window --focus-monitor 1
wsbind = SUPER SHIFT, 2, exec, uwsm-window --focus-monitor 2
wsbind = SUPER SHIFT, 3, exec, uwsm-window --focus-monitor 3
wsbind = SUPER SHIFT, 4, exec, uwsm-window --focus-monitor 4
wsbind = SUPER SHIFT, 5, exec, uwsm-window --focus-monitor 5
wsbind = SUPER SHIFT, 6, exec, uwsm-window --focus-monitor 6
wsbind = SUPER SHIFT, 7, exec, uwsm-window --focus-monitor 7
wsbind = SUPER SHIFT, 8, exec, uwsm-window --focus-monitor 8
wsbind = SUPER SHIFT, 9, exec, uwsm-window --focus-monitor 9


